### ISSUE TITLE
Empty prefix not possible

### ISSUE THREAD

**Issue by JohannesK71083** [qmonnet/git-archive-all-action#1]
In the README is written that the prefix is empty by default. This is not true because when the input for prefix is empty or non existing you don't set the parameter "--prefix" git_archive_all.py and the default inside of git_archive_all.py is the output-filename. This causes the problem that you can't set no prefix, because if you do in the inputs it is treated as if none is set. Solution: set `prefix= ` as parameter if prefix is empty.

**Comment by JohannesK71083** [comment]
@qmonnet I found a workaround: If you set the prefix to /, then it is empty. But you should put that in the documentation: default: output_file_name; override-to-empty: /

**Comment by qmonnet** [comment]
Nice find! Updated in 9ea6ce417247c96788c19da9c0c30d6463601495, thank you
